#!/bin/bash

# Reset
nc='\033[0m'
# Defaults to RED
accent='\033[1;31m'

case "$1" in
  1) accent='\033[1;31m';;
  2) accent='\033[1;32m';;
  3) accent='\033[1;33m';;
  4) accent='\033[1;34m';;
  5) accent='\033[1;35m';;
  6) accent='\033[1;36m';;
  7) accent='\033[1;37m';;
esac

read stdin
echo -e "${accent}$stdin${NC}" 
