#!/usr/bin/env python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

url = "http://192.168.0.1"
password = "Nathan1011"

driver = webdriver.Firefox()

driver.get(url)

element = driver.find_element_by_id('pcPassword')
element.send_keys(password)
element.send_keys(Keys.RETURN)

time.sleep(2)

driver.switch_to.frame("frame1")

element = driver.find_element_by_id('menu_tools')
element.click()
element = driver.find_element_by_id('menu_restart')
element.click()

driver.switch_to.default_content()
driver.switch_to.frame("frame2")

element = driver.find_element_by_id('button_reboot')
element.click()

driver.switch_to.alert.accept();