#!/bin/bash

source "$(ueberzug library)"
[ -z $4 ] && echo "Usage: $0 <image> <x> <y> <width>" && exit
{
  ImageLayer::add [identifier]="image" [path]="$1" [x]="$2" [y]="$3" [width]="$4" [scaler]="contain"
  read
} | ImageLayer
clear
