#!/bin/bash

title=$(xprop -id $(xdotool getwindowfocus) \
  | grep -i class \
  | cut -d' ' -f4)

[ "$1" == "simple" ] && echo $title && exit

title=$(echo $title | sed -e 's/"//g; s/_/ /g; s,\b\(.\),\u\1,g')

echo "$title"
